# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy React and ASP.Net Core app to Azure Web App - ranksterr-app-dev

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      checks: write  # Add this line to grant write permission for checks
      contents: read
      actions: read
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'  # Specify the Node.js version you need

      - name: Run Nextjs npm script
        run: |
          cd ranksterr-next-app 
          npm install      
          npm run testJunit
          npm run build        

      - name: Test Jest Junit Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/jest-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results
          fail-on-error: true
          token: ${{ secrets.GITHUB_TOKEN }}
        
      
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true
     
      - name: Run Ranksterr Application Tests 
        run: | 
          dotnet test Ranksterr.Application.UnitTests/Ranksterr.Application.UnitTests.csproj --configuration Release --logger "trx;LogFileName=test-results-RApp.trx" || true
      
      - name: Run Ranksterr Infrastructure Tests
        run: |
          dotnet test Ranksterr.Infrastructure.UnitTests/Ranksterr.Infrastructure.UnitTests.csproj --configuration Release --logger "trx;LogFileName=test-results-RInf.trx" || true
          
      - name: Run Ranksterr Integration Tests
        run: |
          dotnet test Ranksterr.Api.IntegrationTests/Ranksterr.Api.IntegrationTests.csproj --configuration Release --logger "trx;LogFileName=test-results-RApiInt.trx" || true
      
      - name: Test Report for C#
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: DotNET Tests
          path: "**/test-results*.trx"
          reporter: dotnet-trx
          fail-on-error: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run npm script
        run: |
          cd ranksterr-react-app 
          npm install      
          npm run test
          npm run buildlinux
            
      - name: Write secret to config file
        env:
          API_SETTINGS: ${{secrets.RANKSTERR_API_APPSETTINGS}}
        shell: bash
        run: |
            echo "$API_SETTINGS" > Ranksterr.Api/appsettings.json
            cat Ranksterr.Api/appsettings.json
        
      - name: Build with dotnet
        run: |
          cd Ranksterr.Api/
          dotnet build --configuration Release

      - name: dotnet publish
        run: |
          cd Ranksterr.Api/
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CE5BCCFCD3814A4F808631939FA9E9C3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_27CD7AE92DB343B8A32EE9DF3C873CCC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B4F2E6F7B0BF4BBE9FD6F8300677000C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ranksterr-app-dev'
          slot-name: 'Production'
          package: .
          
